MATCH_FOLDER_NAME="^[a-zA-Z]*$"
MATCH_EXT_NAME="^[a-zA-Z]*$"
MATCH_NUM="^[\+-]?[0-9]*$"
MATCH_FILE_NAME="^[A-Za-z]+((\.[a-zA-Z]{1,3}$)|$)"
MATCH_FILE_NUM="^[\+]?[0-9]*[\.]?[0-9]+$"
MATCH_RESTRICTED_FOLDERS="^(bin\/|sbin\/)$"
FILE_NAME_MASK="^[a-zA-Z]*\.?[a-zA-Z]*_\
[0-9][0-9][0-9][0-9][0-9][0-9]$"
LOG_FILE="^*\.log$"